"""Classifier, grouper, and metadata-parser unit coverage."""
import os

import pandas as pd
import pytest

import core

import _builders

SYN_FILES = {
    "/data/sample_123456.nxs": "o1",
    "/data/sample_123456.hdf": "o2",
    "/data/sample_123456_integration_00.xy": "o3",
    "/data/other_777777.nxs": "o4",
    "/data/orphan_999999.hdf": "o5",
    "/data/sample_123456_extra.xy": "o6",
}


@pytest.fixture
def syn_groups():
    """SynchrotronFileGrouper output over the fixed synchrotron file mix."""
    return core.SynchrotronFileGrouper().group_files(dict(SYN_FILES))


@pytest.mark.parametrize("scan_id, key, expected", [
    pytest.param("123456", "nxs", "/data/sample_123456.nxs", id="anchored-nxs"),
    pytest.param("123456", "hdf", "/data/sample_123456.hdf", id="anchored-hdf"),
    pytest.param("777777", "nxs", "/data/other_777777.nxs", id="lone-nxs-own-group"),
])
def test_synchrotron_grouping(syn_groups, scan_id, key, expected):
    """A .nxs anchors each group; same-ID files join; a lone .nxs still groups."""
    assert syn_groups.get(scan_id, {}).get(key) == expected, str(syn_groups.get(scan_id))


def test_synchrotron_orphan_hdf_stays_ungrouped(syn_groups):
    """An .hdf with no matching .nxs anchor never forms a group."""
    assert "999999" not in syn_groups, str(syn_groups)


def test_synchrotron_integration_xy_joins_group():
    """An _integration_ .xy maps back to its scan ID and joins the anchored group."""
    files = {k: v for k, v in SYN_FILES.items() if k != "/data/sample_123456_extra.xy"}
    groups = core.SynchrotronFileGrouper().group_files(files)
    assert groups["123456"].get("xy") == "/data/sample_123456_integration_00.xy", \
        str(groups.get("123456"))


def test_synchrotron_trailing_id_xy_joins_group(syn_groups):
    """A plain trailing-ID .xy also joins its group; the last file grouped wins the slot."""
    assert syn_groups.get("123456", {}).get("xy") == "/data/sample_123456_extra.xy", \
        str(syn_groups.get("123456"))


def test_neutron_metadata_parse(tmp_path):
    """The builder logbook line parses to one row with scan_id and datetime start/end."""
    path = tmp_path / "logbook.txt"
    path.write_text(_builders.LOGBOOK_LINE + "\n")
    df = core.NeutronMetadataParser.parse(str(path))
    assert df is not None and len(df) == 1
    assert {"scan_id", "start_time", "end_time"} <= set(df.columns), str(df.columns)
    row = df.iloc[0]
    assert row["scan_id"] == "123456", f"got {row['scan_id']}"
    assert row["start_time"] == pd.Timestamp("2024-02-05 10:00:00"), f"got {row['start_time']}"
    assert row["end_time"] == pd.Timestamp("2024-02-05 10:30:00"), f"got {row['end_time']}"


def test_neutron_file_grouping(tmp_path):
    """Builder bank files group as scan -> measurement -> tof/d paths."""
    _builders.write_neutron_banks(str(tmp_path))
    files = [str(tmp_path / name) for name in sorted(os.listdir(tmp_path))]
    groups = core.NeutronFileGrouper().group_neutron_files(files)
    assert set(groups.keys()) == {"123456"}, str(groups)
    assert set(groups["123456"].keys()) == {"1", "2"}, str(groups["123456"])
    for meas in ("1", "2"):
        assert set(groups["123456"][meas].keys()) == {"tof", "d"}, str(groups["123456"][meas])
        assert groups["123456"][meas]["tof"].endswith(f"123456-{meas}-0.dat")
        assert groups["123456"][meas]["d"].endswith(f"123456-{meas}-d-0.dat")


@pytest.mark.parametrize("filename", [
    "123456-1-0.dat", "123456-1-d-0.dat", "123456-2-0.dat", "123456-2-d-0.dat",
])
def test_neutron_extract_scan_id(filename):
    """Every bank filename variant yields the scan ID used for grouping."""
    assert core.NeutronFileGrouper.extract_scan_id(filename) == "123456"


def test_parse_mantid_header(tmp_path):
    """Instrument, X-axis unit, and spectrum number harvest from a Mantid header."""
    path = tmp_path / "mantid.dat"
    path.write_text(
        "# File generated by Mantid, Instrument POLARIS\n"
        "# The X-axis unit is: Time-of-flight, The Y-axis unit is:  per microsecond\n"
        "# Spectrum 1\n"
        "1000.0 51.0 1.0\n")
    info = core.parse_mantid_header(str(path))
    assert info.get("instrument") == "POLARIS", str(info)
    assert info.get("x_unit") == "Time-of-flight", str(info)
    assert info.get("spectrum") == 1, str(info)


def test_txt_classifier_echem_vs_logbook(tmp_path):
    """.txt with echem keywords classifies as echem; a logbook line as neutron_meta."""
    echem = tmp_path / "echem.txt"
    _builders.write_echem_txt(str(echem))
    logbook = tmp_path / "logbook.txt"
    logbook.write_text(_builders.LOGBOOK_LINE + "\n")
    clf = core.TXTClassifier()
    assert clf.classify(str(echem)) == ("echem", None, None)
    assert clf.classify(str(logbook)) == ("neutron_meta", None, None)


def test_dat_classifier_oned(tmp_path):
    """An XRD .dat header classifies as oned with its timestamp and exposure."""
    path = tmp_path / "scan.dat"
    _builders.write_xrd_dat(str(path), _builders.SCAN_TIMES[0])
    assert core.DATClassifier().classify(str(path)) == ("oned", "2024-02-05 10:05:00", 120.0)


def test_classification_manager_inhouse(inhouse_dir):
    """classify_files fills oned/echem columns over the in-house dir and returns a copy."""
    paths = [os.path.join(inhouse_dir, name) for name in sorted(os.listdir(inhouse_dir))]
    df = pd.DataFrame({"path": paths})
    out = core.FileClassificationManager(core.DataSourceType.INHOUSE).classify_files(df)
    assert out is not df and list(df.columns) == ["path"], "input frame must be untouched"
    oned = out[out["oned"].notna()]
    assert sorted(os.path.basename(p) for p in oned["oned"]) == \
        ["scan_001.dat", "scan_002.dat", "scan_003.dat"]
    assert list(oned["timestamp"]) == ["2024-02-05 10:05:00", "2024-02-05 10:10:00",
                                       "2024-02-05 10:15:00"]
    assert list(oned["exposure_time"]) == [120.0, 120.0, 120.0]
    echem_rows = out[out["echem"].notna()]
    assert len(echem_rows) == 1, str(out["echem"].tolist())
    assert os.path.basename(echem_rows["echem"].iloc[0]) == "echem.txt"
